### ISSUE TITLE
Ubuntu Xenial install fails

### ISSUE THREAD

**Issue by raacampbell** [SainsburyWellcomeCentre/lasagna#227]
Doing `pip3 install -r requirements.txt --upgrade` seems to work. I then run `pip3 install -e ./`, as on Mac this created the lasagna loader script. However, running this gets me:

```
Obtaining file:///opt/lasagna/lasagna
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extern.six.moves import filterfalse, map
      File "/usr/lib/python3/dist-packages/setuptools/extern/__init__.py", line 1, in <module>
        from pkg_resources.extern import VendorImporter
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /opt/lasagna/lasagna/
```

The path being:
```
$ pwd
/opt/lasagna/lasagna
$ ls
ARA            compileGUI.sh  lasagna                  LICENSE.txt          mainWindow_rc.py  requirements.txt  setup_windows.py
Changelog.txt  designerFiles  lasagna_environment.yml  loader_dialog_UI.py  README.md         setup.py
```

I also tried:
```
$ sudo python3 setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup, find_packages
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 11, in <module>
    from setuptools.extern.six.moves import filterfalse, map
  File "/usr/lib/python3/dist-packages/setuptools/extern/__init__.py", line 1, in <module>
    from pkg_resources.extern import VendorImporter
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2927, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2913, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2952, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2515, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
```

**Comment by raacampbell** [comment]
@ablot do you know how to get installed on Linux with Python 3.5?

**Comment by adamltyson** [comment]
This works fine on my machine (Ubuntu 18.04 with Python 3.5 & 3.6). I think your error is in pip and/or setuptools. Have you tried `pip install --upgrade pip` & `pip install --upgrade setuptools`?

**Comment by raacampbell** [comment]
Ok, did that and tried on a machine with Bionic running Python 3.6.8 and I'm closer but get a bunch of Qt errors even though Qt is installed:
```
$ lasagna
Traceback (most recent call last):
  File "/usr/local/bin/lasagna", line 11, in <module>
    load_entry_point('Lasagna', 'console_scripts', 'lasagna')()
  File "/home/rob/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/rob/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/home/rob/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/home/rob/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/lasagna/lasagna/lasagna/main.py", line 30, in <module>
    from lasagna.lasagna_object import Lasagna
  File "/opt/lasagna/lasagna/lasagna/lasagna_object.py", line 25, in <module>
    class Lasagna(QtGui.QMainWindow, lasagna_mainWindow.Ui_lasagna_mainWindow):
AttributeError: module 'PyQt5.QtGui' has no attribute 'QMainWindow'
```

**Comment by raacampbell** [comment]
This is so weird. On this machine `QMainWindow` is in `PyQt5.QtWidgets` whereas Lasagna is trying to import it from `PyQt5.QtGui`. Yet this has been working elsewhere. This machine is:

```
>>> from PyQt5.Qt import PYQT_VERSION_STR
>>> print("PyQt version:", PYQT_VERSION_STR)
PyQt version: 5.12.2
```

**Comment by ablot** [comment]
I have pyqt5 5.12.1 but that shouldn't make a difference. I use
python3.7.3.

I think that the issue is related to pyqtgraph:

```
(lasagna) blota@chainsaw:~$ ipython
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from PyQt5 import QtGui


In [2]: QtGui.QMainWindow

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-33e111c0dbfc> in <module>
----> 1 QtGui.QMainWindow

AttributeError: module 'PyQt5.QtGui' has no attribute 'QMainWindow'

In [3]: import pyqtgraph as pg


In [4]: QtGui.QMainWindow

Out[4]: PyQt5.QtWidgets.QMainWindow
```

**Comment by raacampbell** [comment]
Interesting. Same on OS X. I'll look into what's happening.

**Comment by raacampbell** [comment]
Yes, I think I remember now that PyQtGraph added QMainWindow to QtGui like that. I corrected the problem (d961ad7224dd9b7258aedb186b8c24c4dcd98092) but haven't tested again on my new Linux yet.

**Comment by raacampbell** [comment]
Final PyQt5-related fix: 62de80d2e3b1743429ce637052f9af93600ad2b6
Another module was in a different place but I then got:
```
 lasagna
Starting
QWidget: Must construct a QApplication before a QPaintDevice
Aborted (core dumped)
```

Fixed it by placing the `pyqtgraph` import after the `PyQt5`. A bit of hack, but it works.
